language: android

jdk: openjdk7

sudo: false

android:
  components:
  - build-tools-25.0.0
  - android-25
  - extra-android-m2repository
  - extra-android-support

script:
  - "./gradlew assembleRelease"